config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # 5.4.1演習No.1
  get '/signup',  to: 'users#new'
  # 3.4.4演習No.2_コメントアウト解除
  root 'static_pages#home'
  # 5.3.2演習No.1
  # get  '/help',    to: 'static_pages#help', as: 'helf'
  # 5.3.2演習No.3
  # get  '/help',    to: 'static_pages#help'
  # 5.3.3演習No.1
  # get  '/help',    to: 'static_pages#help', as: 'helf'
  # 5.3.3演習No.2
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'up' => 'rails/health#show', as: :rails_health_check
  # 7.3.4演習No.2
  post '/signup',  to: 'users#create'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  # 6.2.5演習No.2
  # before_save { self.email = email.downcase! }
  before_save   :downcase_email
  before_create :create_activation_digest
  # 6.2.4演習No.2
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  # 7.3.3演習No.1
  # validates :password, presence: true, length: { minimum: 5 }
  # validates :password, presence: true, length: { minimum: 6 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  # def User.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                 BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end

  # 9.1.1演習No.2（リスト9.4）
  # def self.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                 BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end

  # ランダムなトークンを返す
  # def User.new_token
  #   SecureRandom.urlsafe_base64
  # end

  # 9.1.1演習No.2（リスト9.4）
  # def self.new_token
  #   SecureRandom.urlsafe_base64
  # end

  # 9.1.1演習No.2（リスト9.5）
  # class << self
      # 渡された文字列のハッシュ値を返す
  #   def digest(string)
  #     cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                   BCrypt::Engine.cost
  #     BCrypt::Password.create(string, cost: cost)
  #   end

      # ランダムなトークンを返す
  #   def new_token
  #     SecureRandom.urlsafe_base64
  #   end
  # end

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    # 9.1.4演習No.2
    # return false if remember_digest.nil?
    # 9.1.4演習No.3
    # return false if remember_digest.nil?

    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    # 11.3.3演習No.1
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    # update(reset_digest: User.digest(reset_token))
    # update(reset_sent_at: Time.zone.now)
    # 12.3.3演習No.1
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
    # 14.3.2演習No.1
    # Micropost.where("user_id IN (?)", following_ids)
    # 14.3.2演習No.2
    # Micropost.where("user_id IN (?)", id)
    # 14.3.2演習No.3
    # Micropost.all
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    # self.email = email.downcase
    # 11.1.2演習No.3
    email.downcase!
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  # 10.4.3演習No.1
  # before_action :admin_user, only: :destroy
  before_action :admin_user, only: :destroy

  def index
    # 11.3.3演習No.2
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  # 10.2.1演習No.1
  # before_action :logged_in_user
  # only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    # 7.1.3演習No.1
    # debugger
    # 11.3.3演習No.2
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    # 7.1.3演習No.2
    # debugger
    @user = User.new(user_params)
    if @user.save
      # 8.2.5演習No.1
      # log_in @user
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
      # 7.4.4演習No.3
      # redirect_to @user
      # 7.4.1演習No.2
      # redirect_to user_url(@user)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      # params.require(:user).permit(:name, :email, :password, :password_confirmation)
      # 10.4.1演習No.1
      # params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  # 7.1.4演習No.2
  # def gravatar_for(user, options = { size: 80 })
  # 7.1.4演習No.3
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    # 7.1.4演習No.3
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%# 10.1.1演習No.2 %>
    <%= render 'layouts/form', { object: @user, url: user_path(@user) } %>
    <%#= form_for(@user) do |f| %>
      <%#= render 'shared/error_messages' %>

      <%#= f.label :name %>
      <%#= f.text_field :name, class: 'form-control' %>

      <%#= f.label :email %>
      <%#= f.email_field :email, class: 'form-control' %>

      <%#= f.label :password %>
      <%#= f.password_field :password, class: 'form-control' %>

      <%#= f.label :password_confirmation, "Confirmation" %>
      <%#= f.password_field :password_confirmation, class: 'form-control' %>

      <%#= f.submit "Save changes", class: "btn btn-primary" %>
    <%# end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%# 10.1.1演習No.1 %>
      <%#<a href="http://gravatar.com/emails" target="_blank">change</a>%>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%# 10.3.4演習No.1 %>
<%#= will_paginate previous_label: '← Previous', next_label: 'Next →' %>

<%# 10.3.4演習No.2 %>
<%= will_paginate previous_label: '← Previous', next_label: 'Next →' %>

<ul class="users">
  <%# 10.3.5演習No.1 %>
  <%#= render @users %>
  <%= render @users %>
</ul>

<%# 10.3.4演習No.1 %>
<%#= will_paginate previous_label: '← Previous', next_label: 'Next →' %>
<%= will_paginate previous_label: '← Previous', next_label: 'Next →' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%# 10.1.1演習No.2 %>
    <%= render 'layouts/form', { object: @user, url: signup_path } %>

    <%# 7.2.1演習No.2 %>
    <%#= form_for(@user) do |foobar| %>
    <%#= 7.3.4演習No.2 %>
    <%#= form_for(@user, url: signup_path) do |f| %>
    <%#= 7.3.4演習No.4 %>
    <%#= form_for(@user) do |f| %>
      <%#= render 'shared/error_messages' %>
      <%#= 7.2.1演習No.1 %>
      <%#= f.label :nome %>
      <%#= f.text_field :nome %>

      <%#= 7.2.1演習No.2 %>
      <%#= foobar.label :name %>
      <%#= foobar.text_field :name %>

      <%#= foobar.label :email %>
      <%#= foobar.email_field :email %>

      <%#= foobar.label :password %>
      <%#= foobar.password_field :password %>

      <%#= foobar.label :password_confirmation, "Confirmation" %>
      <%#= foobar.password_field :password_confirmation %>

      <%#= foobar.submit "Create my account", class: "btn btn-primary" %>

      <%#= f.label :name %>
      <%#= f.text_field :name, class: 'form-control' %>

      <%#= f.label :email %>
      <%#= f.email_field :email, class: 'form-control' %>

      <%#= f.label :password %>
      <%#= f.password_field :password, class: 'form-control' %>

      <%#= f.label :password_confirmation, "Confirmation" %>
      <%#= f.password_field :password_confirmation, class: 'from-control' %>

      <%#= f.submit "Create my account", class: "btn btn-primary" %>
    <%# end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
    
      <%# 13.2.3演習No.1 %>
      <%# h1 %>
      <h1>
        <%#= 7.1.4演習No.2・No.3 %>
        <%= gravatar_for @user, size: 50 %>
        <%= @user.name %>
      </h1>
      <%# /h1 %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts, previous_label: '← Previous', next_label: 'Next →' %>
    <% end %>
  </div>
</div>

<%# 7.1.2演習No.1 %>
<%#= @user.created_at %> <%#= @user.updated_at %> 
<%# 7.1.2演習No.2 %>
<%#<br> %>
<%#= Time.now %> 

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <%# 14.2.3演習No.2 %>
          <%# @users.each do |user| %>
            <%#= link_to gravatar_for(user, size: 30), user %>
          <%# end %>
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%# 14.2.3演習No.2 %>
        <%#= render @users %>
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>